# -- 主菜单 --
# PaperMod 主题菜单配置

[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "博客"
url = "/posts/"
weight = 10

[[main]]
name = "归档"
url = "/archives/"
weight = 15

[[main]]
name = "分类"
url = "/categories/"
weight = 20

[[main]]
name = "标签"
url = "/tags/"
weight = 30

[[main]]
name = "搜索"
url = "/search/"
weight = 40

[[main]]
name = "关于"
url = "/about/"
weight = 50