# -- Congo 主题菜单配置 --

main:
- name: 首页
  pageRef: /
  weight: 1
- name: 博客
  pageRef: posts
  weight: 10
- name: 分类
  pageRef: categories
  weight: 20
- name: 标签
  pageRef: tags
  weight: 30
- name: 关于
  pageRef: about
  weight: 40

