[build]
  publish = "public"
  command = "hugo --gc --minify --baseURL "https://${NETLIFY_PROJECT_PRODUCTION_URL}"

[build.environment]
  HUGO_VERSION = "0.154.5"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  HUGO_ENV = "production"
